apiVersion: v1
kind: Service
metadata:
  name: pipecd-sample-server-active
spec:
  selector:
    app: pipecd-sample-server
  type: ClusterIP
  clusterIP: None  # headless service
  ports:
  - protocol: TCP
    port: 10000  # no targetPort for headless service
---
apiVersion: v1
kind: Service
metadata:
  name: pipecd-sample-server-preview
spec:
  selector:
    app: pipecd-sample-server
  type: ClusterIP
  clusterIP: None # headless service
  ports:
    - protocol: TCP
      port: 10000  # no targetPort for headless service
