apiVersion: v1
kind: Secret
metadata:
  name: env-secret
data:
  MYSQL_CONNECTION: YXBwOlpHZ1E3ZzZkQk43azhBVnFGZnJrOWEycjczVTlZQUIyQHRjcCgxMC42Ni4yMjQuMzozMzA2KS9waXBlY2Rfc2FtcGxlP2NoYXJzZXQ9dXRmOG1iNCZwYXJzZVRpbWU9VHJ1ZSZsb2M9VVRD
